### ISSUE TITLE
homework script - problem with fgets?

### ISSUE THREAD

**Issue by tborisova** [elsys/elsys-teachers-tools#2]
**Steps to reproduce**
- Run the script with args:

```
python hw.py "A" "09" "04"
```

**Expected result**
- tests for task1 should pass

**Actual results**
- the tests does not pass:

```
    task1 error (1 != 0)
```
- NOTE: If you run the script withh args:

```
python hw.py "A" "08" "04"
```

the tests passes. But the problem is not that 09/04/task1.c is not working - when I checked it manually it works and it prints 1 if the number is prime. The difference is that 08 uses scanf and 09 uses fgets...

**Comment by migglu** [comment]
From which class is this 09/04/task1.c ?

**Comment by migglu** [comment]
This is old and irrelevant now?

**Comment by tborisova** [comment]
Don't know. Check It...

**Comment by azlekov** [comment]
Let's say irrelevant
