### ISSUE TITLE
Toml

### ISSUE THREAD

**Issue by migglu** [elsys/elsys-teachers-tools#22]
Do we really need to use toml format for test cases? Isn't yaml a native format for python (not requiring installation of libs?)

**Comment by azlekov** [comment]
Nope, YAML also require installation of third party libs

**Comment by bankin** [comment]
Let's go for JavaScript and JSON and fuck off all this :D

On Tue, Jan 19, 2016 at 9:47 PM, Asen Lekov notifications@github.com
wrote:

> Nope, YAML also require installation of third party libs
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elsys/elsys-teachers-tools/issues/22#issuecomment-172964968
> .

## 

Best regards,
_Nikolay Bankin_
Developer
_email: niky.bankin@gmail.com niky.bankin@gmail.com_

**Comment by azlekov** [comment]
FU
