### ISSUE TITLE
eval.sh does not work

### ISSUE THREAD

**Issue by migglu** [elsys/elsys-teachers-tools#25]
(venv)sasho@debian:~/programs/elsys/elsys-teachers-tools$ ./eval.sh . ../po-homework/ 01
01/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

00/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

-1/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

01/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

00/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

-1/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

01/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

00/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

-1/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

01/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

00/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

-1/01
./eval.sh: line 37: 10#README: value too great for base (error token is "10#README")

**Comment by bankin** [comment]
**Note to self**
1. stop checking hws if numbers is < 1 
2. Fix number converting

**Comment by migglu** [comment]
След "поправката" - http://pastebin.com/ZzE1WH8K

**Comment by bankin** [comment]
Fixed again! AND THE DAY IS SAVED!
