### ISSUE TITLE
If I submit two files for one task I get twice the points

### ISSUE THREAD

**Issue by bankin** [elsys/elsys-teachers-tools#38]
If I have 02_solved.c and 02_soled2.c and task 2 is worth 5 points and the maximum for this is homework is 10 points(we have task1 worth 5 points also) the script will output that I have two times second problem and if I've soled all correct it will tell me that I have 15 points which is over the maximum.

**Comment by bankin** [comment]
<img width="1291" alt="screen shot 2016-10-16 at 23 02 18" src="https://cloud.githubusercontent.com/assets/5245898/19420478/ab746db6-93f4-11e6-9a80-8795e3d46a3f.png">

**Comment by azlekov** [comment]
@bankin забелезах го това и видях де е проблема. Ще се пробвам да го оправя и туй.
