### ISSUE TITLE
Script is failing when there are spaces in the file names

### ISSUE THREAD

**Issue by bankin** [elsys/elsys-teachers-tools#39]

**Comment by azlekov** [comment]
More info?

**Comment by bankin** [comment]
We had 4 files 01_Squares & Cubes.c, 02_Compare 3.c, 03_Min & Max.c, 04_Symethric Letter.c
The script was giving him 0/20 with failed tests result. When putting the flag for --failed-output nothing was changing with his README. When removing the whitespaces from the filenames everything worked correctly for 20/20
